services:
  mlops-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./test:/app/test
    environment:
      - CONFIG_PATH=/app/config.yml
    restart: unless-stopped

  mlops-web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://mlops-api:8000
      - EXTERNAL_IP=51.11.209.9
    depends_on:
      - mlops-api
    restart: unless-stopped

  mlops-flow:
    build:
      context: .
      dockerfile: Dockerfile.api
    command: ["uv", "run", "mlflow", "ui", "--backend-store-uri", "mlruns", "--host", "0.0.0.0", "--port", "5000"]
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/app/mlruns
    environment:
      - CONFIG_PATH=/app/config.yml
    restart: unless-stopped
